### ISSUE TITLE
Problem on my Surface Pro 8

### ISSUE THREAD

**Issue by def000** [X3NOOO/locker#3]
OS: Windows 11
Device: Microsoft Surface Pro 8

When attempting to encrypt my homework folder your software started displaying defamatory pictures of the Polish pope John Paul II. The issue persisted even after a system reboot. 

Here's a video of the incident: https://www.youtube.com/watch?v=wKUMEaq1vgI

Are you proud of yourself? Do you even possess the common sense and dignity of a man?

I will no longer continue financially supporting your Jewish little schemes to destroy the white race and defaming our national heroes. 

I wish you a very miserable Hannukah!
Patryk Bejca.

**Comment by X3NOOO** [comment]
![epic troll](https://user-images.githubusercontent.com/48159366/149823049-dd47bb0e-2bff-401d-8be2-ea4f76aec044.png)
